#3903 - Send basic message to RTGS on proof presentation
RTGS-OpenSource/rtgs-idcrypt-service pull request #37
Opened 2022-06-06 15:32 UTC by DavidRamsbottomRTGS

2022-06-06 15:53 UTC, Bassetts requested changes

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service/Repositories/RtgsConnectionRepository.cs
> +				.Where(connection =>
`connection` hides the outer variable

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Webhooks/Handlers/PresentProofHandlerTests/GivenProofPresentation.cs
> +	private readonly Mock<IRtgsConnectionRepository> _rtgsConnectionRepositoryMock;
This can be a local

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Repositories/RtgsConnectionRepository/GivenGetEstablishedRequest/AndTableStorageUnavailable.cs
> +			.Should().BeEquivalentTo("Error occurred when getting connection");
Should this error be `"Error occurred when getting RTGS connection"` instead?

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Repositories/RtgsConnectionRepository/GivenGetEstablishedRequest/AndConnectionDoesNotExist.cs
> +		const int maximumConnectionAgeInMinues = 5;
```suggestion
		const int maximumConnectionAgeInMinutes = 5;
```

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Repositories/RtgsConnectionRepository/GivenActivateAsyncRequest/AndConnectionDoesNotExist.cs
> -	public void ThenExpectedTableIsResolved() => _storageTableResolverMock.Verify();
There is also a unused variable in the constructor here: `retrievedConnection`

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Repositories/BankPartnerConnectionRepository/GivenGetAsyncRequest/AndTableStorageAvailable.cs
> +		};
Variable is not used

2022-06-06 15:53 UTC, Bassetts commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Repositories/BankPartnerConnectionRepository/GivenDeleteAsyncRequest/AndConnectionDoesNotExist.cs
> -	public void ThenExpectedTableIsResolved() => _storageTableResolverMock.Verify();
`_storageTableResolverMock` can be a local variable now

2022-06-06 16:07 UTC, DavidRamsbottomRTGS commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.IntegrationTests/Fixtures/Connection/RtgsConnectionDoesNotExistFixture.cs
> +			CreatedAt = DateTime.UtcNow,
Perhaps - not sure how, and not sure if there is a huge benefit?

2022-06-07 08:18 UTC, Bassetts approved these changes

2022-06-07 08:20 UTC, merged