Feature/4027 verify active connection
RTGS-OpenSource/rtgs-idcrypt-service pull request #70
Opened 2022-07-01 15:40 UTC by DavidRamsbottomRTGS

2022-07-01 16:10 UTC, Darren-Osborne requested changes

2022-07-01 16:10 UTC, Darren-Osborne commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Webhooks/Handlers/IdCryptBasicMessageHandlerTests/GivenBasicMessageFromBank/AndHandlerExists/NotRequiringActiveConnection/AndConnectionIsNotActive.cs
> +}
Got a little confused - only differecce between this and the previous file is that Source is specified in one and not the other. Bit of a tenious link between that the the connection being active or not??

2022-07-01 16:10 UTC, Darren-Osborne commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Webhooks/Handlers/IdCryptBasicMessageHandlerTests/GivenBasicMessageFromRtgs/AndHandlerExists/NotRequiringActiveConnection/AndConnectionIsActive.cs
> +			Mock.Of<IRtgsConnectionRepository>(),
Similar to other comment - i'd expect to see one of the repos returning an active connection?

2022-07-04 07:57 UTC, DavidRamsbottomRTGS commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Webhooks/Handlers/IdCryptBasicMessageHandlerTests/GivenBasicMessageFromBank/AndHandlerExists/NotRequiringActiveConnection/AndConnectionIsNotActive.cs
> +}
Because the handler doesn't need an active connection the repo itself is never queried.  You are right though that the test files are basically the same as each other, but we struggled a bit to think of a sensible way of doing something about that.  Any thoughts?

2022-07-04 07:58 UTC, DavidRamsbottomRTGS commented on src/RTGS.IDCrypt.Service/RTGS.IDCrypt.Service.Tests/Webhooks/Handlers/IdCryptBasicMessageHandlerTests/GivenBasicMessageFromRtgs/AndHandlerExists/NotRequiringActiveConnection/AndConnectionIsActive.cs
> +			Mock.Of<IRtgsConnectionRepository>(),
Ditto above - repo is never called.

2022-07-04 08:30 UTC, Darren-Osborne approved these changes

2022-07-04 08:41 UTC, merged